name: Update requirements file
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
  
      - name: Generate requirements file
        id: Requirements_file

        uses: ryan-rozario/pipreqs-action-cpy@master

        with:
          PROJECT_PATH: ./src
          REQUIREMENT_PATH: ./src/requirements.txt